apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php-k8s-sample:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
